project:
  type: website

website:
  page-navigation: true
  title: "CRP-PAM Lab Manual"
  site-url: "https://pifsc-protected-species-division.github.io/CRP_PAM_Manual/"
  repo-url: "https://github.com/PIFSC-Protected-Species-Division/CRP_PAM_Manual"
  repo-actions: [edit, source, issue]
  favicon: content/images/favicon.ico

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    background: "#BDCCD2"
    # background: "#CDFEFF"
    # background: "#D9E3E4" #original
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.fisheries.noaa.gov/pacific-islands/population-assessments/passive-acoustics-pacific-islands
        text: "NOAA Fisheries PIFSC - Passive Acoustic Monitoring"
        target: _blank
      - icon: github
        href: https://github.com/PIFSC-Protected-Species-Division
        text: "NOAA Fisheries PIFSC Protected Species Division"
        target: _blank


    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: content/LabManagement.qmd
        contents:
          - href: content/Safety.qmd
            text: Safety
      - href: content/FieldMethods.qmd
        text: Field Methods
      - section: content/DataManagement.qmd
        text: Data Management
        contents:
        - href: content/GCPUpload.qmd
          text: GCP Data Upload
      - section: content/Hardware.qmd
        contents:
        - href: content/Inventory.qmd
          text: Inventory
        - href: content/TA_Depth.qmd
          text: Towed Array Depth 
      - section: content/SoftwareAnalysis.qmd
        text: Software & Analysis
        contents:
        # - href: content/Software.qmd
        - href: content/PAMGuard.qmd
          text: PAMGuard User Tips
        # - href: content/AnalysisMethods.qmd
      - href: content/Reporting.qmd
        text: Reporting
      - href: content/PublicationsPresentations.qmd
        text: Publications Presentations
      # - section: "Optional Pages"
        # contents:
          # - content/SharedValues.qmd
          # - content/Onboarding.qmd
          # - content/Offboarding.qmd
          # - content/FieldMethods.qmd
          # - content/OpenScience.qmd
          # - content/PublicationsPresentations.qmd
          # - content/Resources.qmd
      - section: "NMFS Open Science Directions"
        contents:
          - content/NMFS_OpenSciDirections/Intro.qmd
          - content/NMFS_OpenSciDirections/add-content.qmd
          - content/NMFS_OpenSciDirections/customizing.qmd
          - content/NMFS_OpenSciDirections/rendering.qmd
          - content/NMFS_OpenSciDirections/rmarkdown.Rmd
          - content/NMFS_OpenSciDirections/code.qmd
          - content/NMFS_OpenSciDirections/acknowledgements.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto


